FROM python:3.11.1-slim

# set env variables
ENV DEBIAN_FRONTEND='noninteractive'
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update 
RUN apt-get install -y iputils-ping

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

WORKDIR /backup_db
WORKDIR /app
COPY ./app .

EXPOSE 8000

CMD [ "gunicorn", "-w",  "4", "-k", "uvicorn.workers.UvicornWorker", "api:app" ]