FROM python:3.11.1-slim

# set env variables
ENV DEBIAN_FRONTEND='noninteractive'
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update 
RUN apt-get install -y iputils-ping

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

WORKDIR /dashboard
COPY ./dashboard .

EXPOSE 8050

CMD [ "python", "demo_dashboard_base"]